gnodeb:
  controlif:
    ip: "127.0.0.1"
    port: 9487
  dataif:
    ip: "10.200.200.2"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000002"
  slicesupportlist:
    st: "01"
    sst: "010203"
ue:
  imsi: "imsi-2089300000223"
  key: "70d49a71dd1a2b806a25abe0ef749f1e"
  opc: "6f1bf53d624b3a43af6592854e2444c7"
  amf: "8000"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sd: 1
    sst: "010203"
  ping: "60.60.0.101"
amfif:
  ip: "127.0.0.1"
  port: 38412
  name: "free5gc"
upfif:
  ip: "10.200.200.102"
  port: 2152