gnodeb:
  controlif:
    ip: "192.168.11.13"
    port: 9487
  dataif:
    ip: "192.168.11.13"
    port: 2152
  plmnlist:
    mcc: "999"
    mnc: "70"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    sd: "000001" # optional, can be removed if not used

ue:
  msin: "0000001000"
  key: "00112233445566778899AABBCCDDEEFF"
  opc: "00112233445566778899AABBCCDDEEFF"
  amf: "8000"
  sqn: "00000000"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "999"
    mnc: "70"
  snssai:
    sst: 01
    sd: "000001" # optional, can be removed if not used
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false
amfif:
  ip: "192.168.11.30"
  port: 38412
logs:
    level: 5
