gnodeb:
  controlif:
    ip: "192.168.10.108"
    port: 9487
  dataif:
    ip: "192.168.10.108"
    port: 2152
  plmnlist:
    mcc: "901"
    mnc: "70"
    tac: "000001"
    gnbid: "000001"
  slicesupportlist:
    sst: "01"
    sd: "010203"

ue:
  msin: "00000001"
  key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  amf: "8000"
  sqn: "0000000"
  dnn: "internet"
  hplmn:
    mcc: "901"
    mnc: "70"
  snssai:
    sst: 01
    sd: ""

amfif:
  ip: "192.168.122.83"
  port: 38412
  name: "open5gs"
